const r = require('express').Router();
const c = require('../controllers/responseController');
const { protect } = require('../middleware/auth');
const superAdmin = require('../middleware/superAdmin');
r.get('/mine', protect, c.mine);
r.get('/', protect, superAdmin, c.getAll);
r.get('/post/:postId', c.getByPost);
r.post('/post/:postId', protect, c.create);
r.put('/:id', protect, superAdmin, c.update);
r.delete('/:id', protect, c.remove);
module.exports = r;
