const r = require('express').Router();
const c = require('../controllers/userController');
const { protect } = require('../middleware/auth');
const admin = require('../middleware/admin');
const superAdmin = require('../middleware/superAdmin');
r.delete('/me', protect, c.deleteMe);
r.use(protect, admin);
r.get('/stats', c.stats); r.get('/', c.getUsers);
r.put('/:id/block', c.toggleBlock); r.delete('/:id', c.removeUser);
r.put('/promote', superAdmin, c.promoteByEmail);
r.put('/:id/role', superAdmin, c.updateAdminRole);
module.exports = r;
